projects:
  mShoppingWorld:
    schemaPath: amplify/backend/api/mShoppingWorld/build/schema.graphql
    includes:
      - graphql/
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
        region: us-east-1
        apiId: null
        maxDepth: 5
extensions:
  amplify:
    version: 3
